// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://iheuyyfxgjqywmkfrphu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloZXV5eWZ4Z2pxeXdta2ZycGh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNTU2OTcsImV4cCI6MjA4ODYzMTY5N30._60g0Vr7W-m8v3LOGe-BEi8k0TLIfsJRL6Z6k8p-sTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Validate publishable key at runtime and give a clear error if it's for a different project
function tryDecodeJwtPayload(token: string) {
  try {
    const parts = token.split('.');
    if (parts.length < 2) return null;
    const payload = parts[1].replace(/-/g, '+').replace(/_/g, '/');
    const json = decodeURIComponent(atob(payload).split('').map(function(c) {
      return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
    }).join(''));
    return JSON.parse(json);
  } catch (e) {
    return null;
  }
}

// perform a lightweight check so developers see a helpful message instead of `AuthApiError: Invalid API key`
try {
  const projectHost = new URL(SUPABASE_URL).host; // e.g. iheuyyfxgjqywmkfrphu.supabase.co
  const projectIdFromHost = projectHost.split('.')[0];
  const payload = tryDecodeJwtPayload(SUPABASE_PUBLISHABLE_KEY);
  const keyRef = payload?.re || payload?.ref || payload?.aud || payload?.sub;
  if (keyRef && typeof keyRef === 'string' && keyRef !== projectIdFromHost) {
    console.error(`Supabase publishable key mismatch: key belongs to '${keyRef}' but SUPABASE_URL project is '${projectIdFromHost}'. Update VITE_SUPABASE_PUBLISHABLE_KEY in your .env to the project's anon/public key.`);
  }
} catch (e) {
  // ignore any issues in environments where URL or atob aren't available
}